[build]
 command = "npm run build"
  publish = ".output/public"
  functions = ".output/server"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "server/utils/supabaseAdmin.js"

[[headers]]
  for = "/_nuxt/builds/meta/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_nuxt/builds/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

    [[redirects]]
  from = "/*"
  to = "/"
  status = 200