//Stores all monsters the player can fight.

export const monsterCatalog = [
  {
    id: 1,
    name: "Desert Rat",
    level: 1,
    xpPayout: 15,
    strength: 5,
    speed: 10,
    vitality: 10,
    attack: 0,
    evasion: 5,
    block: 0,
    initiative: 5,
    fatigue: 150,
    hp: 200,
    weapon: {
      name: "Crooked Teeth",
      minDmg: 1,
      maxDmg: 4,
      skillReq: 0,
      category: "attack",
    },
    armour: { name: "Dirty Fur", damageReduction: 0 },
    description: "This lil' guy carries all the diseases.",
  },
  {
    id: 2,
    name: "Goblin Mugger",
    level: 1,
    xpPayout: 20,
    strength: 15,
    speed: 10,
    vitality: 15,
    attack: 20,
    evasion: 0,
    block: 0,
    initiative: 3,
    fatigue: 10,
    hp: 25,
    weapon: {
      name: "Rusty Dagger",
      minDmg: 1,
      maxDmg: 5,
      skillReq: 0,
      category: "attack",
    },
    armour: { name: "Rags", damageReduction: 0 },
    description: "The little shits are everywhere.",
  },
  {
    id: 3,
    name: "Bandit",
    level: 2,
    xpPayout: 25,
    strength: 15,
    speed: 10,
    vitality: 15,
    attack: 20,
    evasion: 0,
    block: 0,
    initiative: 10,
    fatigue: 10,
    hp: 35,
    weapon: {
      name: "Club",
      minDmg: 2,
      maxDmg: 6,
      skillReq: 0,
      category: "attack",
    },
    armour: { name: "Ragged Tunic", damageReduction: 0 },
    description: "A run of the mill lowlife.",
  },
];

export const viewMonsterCollection = monsterCatalog.map((monster) => ({
  id: monster.id,
  name: monster.name,
  level: monster.level,
  weapon: monster.weapon,
  armour: monster.armour,
  description: monster.description,
}));
