//Stores all monsters the player can fight.

export const monsterCatalog = [
  {
    id: 1,
    name: "Desert Rat",
    level: 1,
    xpPayout: 15,
    strength: 5,
    speed: 10,
    vitality: 10,
    attack: 5,
    evasion: 5,
    block: 0,
    initiative: 5,
    fatigue: 12,
    hp: 15,
    weapon: {
      name: "Crooked Teeth",
      minDmg: 1,
      maxDmg: 4,
      skillReq: 0,
      category: "attack",
    },
    armour: { name: "Dirty Fur", damageReduction: 0 },
    description: "This lil' guy carries all the diseases.",
  },
  {
    id: 2,
    name: "Goblin Mugger",
    level: 1,
    xpPayout: 20,
    strength: 10,
    speed: 5,
    vitality: 15,
    attack: 10,
    evasion: 0,
    block: 0,
    initiative: 0,
    fatigue: 10,
    hp: 20,
    weapon: {
      name: "Rusty Dagger",
      minDmg: 1,
      maxDmg: 5,
      skillReq: 0,
      category: "attack",
    },
    shield: {
      name: "Dented Buckler",
      blockValue: 1,
      skillReq: 10,
      category: "shields",
    },
    armour: { name: "Rags", damageReduction: 0 },
    description: "The little shits are everywhere.",
  },
  {
    id: 3,
    name: "Bandit",
    level: 2,
    xpPayout: 25,
    strength: 15,
    speed: 10,
    vitality: 15,
    attack: 20,
    evasion: 0,
    block: 0,
    initiative: 10,
    fatigue: 8,
    hp: 30,
    weapon: {
      name: "Club",
      minDmg: 2,
      maxDmg: 6,
      skillReq: 0,
      category: "attack",
    },
    armour: { name: "Ragged Tunic", damageReduction: 0 },
    description: "A run of the mill lowlife.",
  },
  {
    id: 4,
    name: "Grey Wolf",
    level: 2,
    xpPayout: 25,
    strength: 20,
    speed: 10,
    vitality: 10,
    attack: 10,
    evasion: 0,
    block: 0,
    initiative: 10,
    fatigue: 9,
    hp: 25,
    weapon: {
      name: "Yellow Fangs",
      minDmg: 2,
      maxDmg: 6,
      skillReq: 0,
      category: "attack",
    },
    armour: { name: "Grey Fur", damageReduction: 0 },
    description: "A pair of yellow eyes pierce the gloom.",
  },
  {
    id: 5,
    name: "Goblin Raider",
    level: 4,
    xpPayout: 25,
    strength: 30,
    speed: 10,
    vitality: 10,
    attack: 15,
    evasion: 0,
    block: 5,
    initiative: 10,
    fatigue: 8,
    hp: 40,
    weapon: {
      name: "Iron Sabre",
      minDmg: 2,
      maxDmg: 5,
      skillReq: 0,
      category: "attack",
    },
    shield: {
      name: "Buckler",
      blockValue: 1,
      skillReq: 10,
      category: "shields",
    },
    armour: { name: "Patched Leather", damageReduction: 0 },
    description: "They loot and pillage. It's all they know.",
  },
  {
    id: 6,
    name: "Angvarian Bull",
    level: 4,
    xpPayout: 25,
    strength: 30,
    speed: 10,
    vitality: 10,
    attack: 20,
    evasion: 0,
    block: 0,
    initiative: 20,
    fatigue: 10,
    hp: 45,
    weapon: {
      name: "Wicked Horns",
      minDmg: 3,
      maxDmg: 6,
      skillReq: 0,
      category: "attack",
    },
    armour: { name: "Grey Fur", damageReduction: 0 },
    description: "A ferocious bull from the southern plains.",
  },
  {
    id: 7,
    name: "Legion Conscript",
    level: 6,
    xpPayout: 25,
    strength: 30,
    speed: 10,
    vitality: 10,
    attack: 20,
    evasion: 15,
    block: 15,
    initiative: 0,
    fatigue: 12,
    hp: 55,
    weapon: {
      name: "Bronze Spear",
      minDmg: 3,
      maxDmg: 8,
      skillReq: 0,
      category: "attack",
    },
    shield: {
      name: "Small Shield",
      blockValue: 1,
      skillReq: 10,
      category: "shields",
    },
    armour: { name: "Leather Tunic", damageReduction: 1 },
    description: "Drafted into service, wanting a way out. Through you.",
  },
  {
    id: 8,
    name: "Young Troll",
    level: 8,
    xpPayout: 25,
    strength: 30,
    speed: 10,
    vitality: 10,
    attack: 20,
    evasion: 0,
    block: 0,
    initiative: 20,
    fatigue: 15,
    hp: 75,
    weapon: {
      name: "Big Club",
      minDmg: 4,
      maxDmg: 12,
      skillReq: 0,
      category: "attack",
    },
    armour: { name: "Thick Hide", damageReduction: 3 },
    description: "Troll, with a club. They're both pretty big.",
  },
];

export const viewMonsterCollection = monsterCatalog.map((monster) => ({
  id: monster.id,
  name: monster.name,
  level: monster.level,
  weapon: monster.weapon,
  shield: monster.shield,
  armour: monster.armour,
  description: monster.description,
}));
